#
#  CLOUDERA APPLIED MACHINE LEARNING PROTOTYPE (AMP)
#  (C) Cloudera, Inc. 2025
#  All rights reserved.
#
#  Applicable Open Source License: Apache 2.0
#
#  NOTE: Cloudera open source products are modular software products
#  made up of hundreds of individual components, each of which was
#  individually copyrighted.  Each Cloudera open source product is a
#  collective work under U.S. Copyright Law. Your license to use the
#  collective work is as provided in your written agreement with
#  Cloudera.  Used apart from the collective work, this file is
#  licensed for your use pursuant to the open source license
#  identified above.
#
#  This code is provided to you pursuant a written agreement with
#  (i) Cloudera, Inc. or (ii) a third-party authorized to distribute
#  this code. If you do not have a written agreement with Cloudera nor
#  with an authorized and properly licensed third party, you do not
#  have any rights to access nor to use this code.
#
#  Absent a written agreement with Cloudera, Inc. ("Cloudera") to the
#  contrary, A) CLOUDERA PROVIDES THIS CODE TO YOU WITHOUT WARRANTIES OF ANY
#  KIND; (B) CLOUDERA DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED
#  WARRANTIES WITH RESPECT TO THIS CODE, INCLUDING BUT NOT LIMITED TO
#  IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND
#  FITNESS FOR A PARTICULAR PURPOSE; (C) CLOUDERA IS NOT LIABLE TO YOU,
#  AND WILL NOT DEFEND, INDEMNIFY, NOR HOLD YOU HARMLESS FOR ANY CLAIMS
#  ARISING FROM OR RELATED TO THE CODE; AND (D)WITH RESPECT TO YOUR EXERCISE
#  OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, CLOUDERA IS NOT LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR
#  CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES
#  RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF
#  BUSINESS ADVANTAGE OR UNAVAILABILITY, OR LOSS OR CORRUPTION OF
#  DATA.
#

import logging
import re
from pathlib import Path
from typing import Any, List

from docling.datamodel.base_models import InputFormat
from docling.datamodel.document import ConversionResult, PictureItem
from docling.datamodel.pipeline_options import EasyOcrOptions, PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.transforms.chunker.base import BaseChunk
from docling_core.transforms.chunker.hybrid_chunker import HybridChunker
from llama_index.core.schema import Document, NodeRelationship, TextNode

from .base_reader import BaseReader, ChunksResult
from .pdf import MarkdownSerializerProvider

logger = logging.getLogger(__name__)


def clean_ocr_kerning(text: str) -> str:
    """Repairs split single-letter spaces and invalid Unicode generated by OCR engines."""
    # 1. Join single capitalized letters separated by spaces (e.g., "O TO M O TIF" -> "OTOMOTIF")
    cleaned = re.sub(r"(?<=\b[A-Za-z])\s+(?=[A-Za-z]\b)", "", text)
    # 2. Fix broken single-letter word endings (e.g., "M A W X" -> "MAWX")
    cleaned = re.sub(r"\b([A-Za-z]+)\s+([A-Za-z]{1,2})\b", r"\1\2", cleaned)
    # 3. Replace non-printable private Unicode replacement characters (\ue353) with colons
    cleaned = re.sub(r"[\ue000-\uf8ff]", ":", cleaned)
    return cleaned


class DoclingReader(BaseReader):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

    def load_chunks(self, file_path: Path) -> ChunksResult:
        document = Document()
        document.id_ = self.document_id
        self._add_document_metadata(document, file_path)
        parent = document.as_related_node_info()

        # 1. OCR Options: Upscale DPI for high-definition text & grid detection
        pipeline_options = PdfPipelineOptions()
        pipeline_options.do_ocr = True
        pipeline_options.do_table_structure = True
        pipeline_options.ocr_options = EasyOcrOptions(scale=3.0)

        converter = DocumentConverter(
            allowed_formats=[InputFormat.PDF],
            format_options={
                InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
            },
        )

        logger.debug(f"Processing PDF with Docling: {file_path=}")
        docling_doc: ConversionResult = converter.convert(file_path)

        # 2. Chart Extraction: Recover numerical text locked inside Picture / Bar Chart items
        for item, _ in docling_doc.document.iterate_items():
            if isinstance(item, PictureItem):
                if hasattr(item, "annotations") and item.annotations:
                    chart_text = " ".join(
                        [ann.text for ann in item.annotations if hasattr(ann, "text")]
                    )
                    if chart_text:
                        item.text = f"[CHART DATA]: {chart_text}"

        # 3. Hybrid Chunker: Increase token budget to 4096 to prevent table fragmentation
        chunker = HybridChunker(
            serializer_provider=MarkdownSerializerProvider(),
            max_tokens=4096,
            merge_peers=True,
        )
        chunky_chunks = chunker.chunk(docling_doc.document)

        converted_chunks: List[TextNode] = []

        for i, chunky_chunk in enumerate(chunky_chunks):
            page_number: int = 0
            if not hasattr(chunky_chunk.meta, "doc_items"):
                continue

            raw_text = chunky_chunk.text

            # 4. Filter Empty Borders: Skip chunks containing only hyphens and pipes
            clean_check = (
                raw_text.replace("|", "").replace("-", "").replace("\n", "").strip()
            )
            if not clean_check:
                logger.warning(
                    f"Chunk {i} contains only empty markdown formatting, skipping."
                )
                continue

            # 5. Kerning Normalization: Clean up split spaces in OCR output
            normalized_text = clean_ocr_kerning(raw_text)

            for item in chunky_chunk.meta.doc_items:
                page_number = item.prov[0].page_no if item.prov else None

            node = TextNode(text=normalized_text)
            if page_number:
                node.metadata["page_number"] = page_number
            node.metadata["file_name"] = document.metadata["file_name"]
            node.metadata["document_id"] = document.metadata["document_id"]
            node.metadata["data_source_id"] = document.metadata["data_source_id"]
            node.metadata["chunk_number"] = i
            node.metadata["chunk_format"] = "markdown"
            node.relationships.update({NodeRelationship.SOURCE: parent})

            converted_chunks.append(node)

        return ChunksResult(converted_chunks)